### ISSUE TITLE
Text on image

### ISSUE THREAD

**Issue by fatemeh-ta** [VahidD20/architect#5]
is not align BR:
![Screenshot from 2024-07-28 17-35-49](https://github.com/user-attachments/assets/faca9f0a-cf1b-4fc7-92a9-68afccf6830b)

why do you use div and span??explain your reason
![Screenshot from 2024-07-28 17-36-57](https://github.com/user-attachments/assets/7eea4c47-3017-4d2d-81ba-2ee4fa0e6a38)

**Comment by VahidD20** [comment]
I wanted to avoid multiple div. but I ll reform it
